spring:
  application:
    name: check-in
 # datasource:
 #   url: jdbc:mysql://localhost:3306/poc?useSSL=false
 #   username: AppAdmin
 #   password: AppPass@1988
  #  driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: skola2@gmail.com
    password: MIracle@123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true






